site_name: Vitasite Documentation
pages:
- 'Get Started': index.md
- Pages: page.md
- Content: content.md
- Media: upload.md
- 'Photo Features': feature.md
theme: readthedocs
markdown_extensions:
    - admonition
site_url: http://docs.vitasite.com
repo_url: https://github.com/Alliance-Software/vitasite-docs
site_author: Alliance Software
site_description: 'Online documentation for the VitaSite Content Management System (CMS)'
copyright: '&copy; Alliance Software. All Rights Reserved.'
site_favicon: favicon.ico
google_analytics: ['UA-81314-1', 'vitasite.com']